### ISSUE TITLE
Current journey generation is impossible to understand

### ISSUE THREAD

**Issue by seriousbee** [seriousbee/Oyster#10]
Lines like these break any clean code rules. Please delegate this to an external method and clean code it somehow (don't put everything on one line) so others can follow what is going on

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L38

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L39

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L42

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L53

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L60

**Comment by dragospopa** [comment]
impossible to understand if u do not have perspective

**_SOLVED_**
