### ISSUE TITLE
Date and time based on locale

### ISSUE THREAD

**Issue by seriousbee** [seriousbee/Oyster#11]
https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/src/com/tfl/billing/Journey.java#L46

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/src/com/tfl/billing/Journey.java#L50

These lines should be based on locale

**Comment by dragospopa** [comment]
https://github.com/seriousbee/Oyster/pull/13
