### ISSUE TITLE
Peak and off peak journeys need testing

### ISSUE THREAD

**Issue by seriousbee** [seriousbee/Oyster#12]
We need a way of simulating time to check if people would be charged a correct amount of money for journeys in different times of the day

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java

**Comment by dragospopa** [comment]
https://github.com/seriousbee/Oyster/pull/13
