### ISSUE TITLE
Customer charging tests fail

### ISSUE THREAD

**Issue by seriousbee** [seriousbee/Oyster#9]
The following tests don't pass:
https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L82-L85
`
Expected :is <2.40>
Actual   :<1.60>
`

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L94-L97
`
Expected :is <0.00>
Actual   :<3.20>
`

https://github.com/seriousbee/Oyster/blob/7c1cf3598bd04b5cf28f538c29f471b02b2ab056/test/com/tfl/billing/JourneyCostCalculatorTest.java#L88-L91
`
Expected :is <4.80>
Actual   :<3.20>
`

**Comment by dragospopa** [comment]
https://github.com/seriousbee/Oyster/pull/13
